export const strings = {
  home: {
    greeting: 'Olá, {name} 👋',
    subtitle: 'Você tem 1 treino hoje',
    title: 'ProTrack',
    progress: 'Progresso da semana',
    activeWorkoutBanner: 'Treino em andamento — toque para continuar',
  },
  buildWorkout: {
    title: 'Montar Treino',
    subtitle: 'Crie um treino personalizado',
    mainPlanName: 'Nome Principal do Plano',
    placeholderPlanName: 'Ex: PPL do João',
    partitionNamePlaceholder: 'Nome da Ficha',
    emptyPartition: 'Nenhum exercício nesta ficha.',
    series: 'Séries',
    reps: 'Repetições',
    addExercise: 'Adicionar Exercício',
    addPartition: '+ Adicionar repartição',
    savePlan: 'Salvar Plano',
    selectExerciseModal: 'Selecionar Exercício',
    defaultWorkoutName: 'Meu Treino',
    defaultPartitionName: 'Treino A',
    alertRemovePartitionTitle: 'Remover repartição?',
    alertRemovePartitionMsg: 'Todos os exercícios desta ficha serão perdidos.',
    cancel: 'Cancelar',
    remove: 'Remover',
    noName: 'Sem nome',
  },
  chooseWorkout: {
    title: 'Iniciar Treino',
    buildNewWorkout: 'Montar Novo Treino',
    buildNewWorkoutSub: 'Crie um treino do zero, do seu jeito.',
    chooseSavedWorkout: 'ESCOLHER TREINO SALVO',
    emptySavedWorkouts: 'Você ainda não salvou nenhum treino. Monte um novo para vê-lo aqui.',
    selectPartitionHeader: 'Selecione a ficha:',
    exerciseShort: 'ex.',
    startWorkoutBtn: 'Iniciar Treino',
  },
  editWorkout: {
    title: 'Editar Treino',
    placeholderEditName: 'Ex: Treino A - Costas',
    alertDeleteWorkoutTitle: 'Excluir treino?',
    alertDeleteWorkoutMsg: 'Essa ação não pode ser desfeita.',
    delete: 'Excluir',
    saveChangesBtn: 'Salvar Alterações',
  },
  myWorkouts: {
    title: 'MEUS TREINOS (CUSTOMIZADOS)',
    sheetSingular: 'ficha',
    sheetPlural: 'fichas',
    editBtn: 'Editar',
  },
  weeklyStats: {
    sectionTitle: 'TREINOS',
    total: 'Total Treinos',
    month: 'Treinos Mês',
    week: 'Treinos Semana',
  },
  featured: {
    sectionTitle: 'PLANOS EM DESTAQUE',
    exercises: 'exercícios',
    empty: 'Nenhum plano em destaque no momento.',
  },
  workoutHistory: {
    title: 'HISTÓRICO DE TREINOS',
    loading: 'Carregando histórico...',
    empty: 'Nenhum treino finalizado ainda.',
    finishedWorkoutTitle: 'Treino Finalizado',
    min: 'min',
    kg: 'kg',
    sets: 'séries',
  },
  activeWorkout: {
    finishBtn: 'Finalizar Treino',
    skipRest: 'Pular Descanso',
    nextExercise: 'Próximo Exercício',
    loading: 'Carregando...',
    alertCancelTitle: 'Cancelar Treino?',
    alertCancelMsg: 'Você perderá o progresso desta sessão.',
    alertCancelNo: 'Não',
    alertCancelYes: 'Sim, Cancelar',
    alertErrorTitle: 'Erro',
    alertErrorMsg: 'Não foi possível salvar o treino.',
    defaultSessionName: 'Treino de Força (Costas)',
    defaultEx1Name: 'Puxada Frontal',
    defaultEx2Name: 'Remada Curvada',
    defaultMuscleName: 'Dorsais',
  },
  profile: {
    title: 'Perfil',
    editProfile: 'Editar Perfil',
    settings: 'Configurações',
    subscription: 'Assinatura',
    help: 'Ajuda e Suporte',
    logout: 'Sair',
    defaultUserName: 'Usuário ProTrack',
    defaultUserEmail: 'sem-email@protrack.app',
  },
  tabs: {
    home: 'Home',
    newWorkout: 'Novo Treino',
    profile: 'Perfil',
  },
  common: {
    loading: 'Carregando...',
    error: 'Ocorreu um erro',
  },
  auth: {
    appName: 'ProTrack',
    subtitleLogin: 'Acesse seus treinos de qualquer lugar.',
    subtitleRegister: 'Crie sua conta e revolucione seus treinos.',
    nameLabel: 'Nome completo',
    namePlaceholder: 'Ex: Pedro Vieira',
    emailLabel: 'E-mail',
    emailPlaceholder: 'seu@email.com',
    passwordLabel: 'Senha',
    passwordPlaceholder: '••••••••',
    confirmPasswordLabel: 'Confirmar Senha',
    loginBtn: 'Entrar',
    registerBtn: 'Criar Conta',
    dontHaveAccount: 'Não tem uma conta? ',
    signUpLink: 'Cadastre-se',
    alreadyHaveAccount: 'Já tem conta? ',
    loginLink: 'Fazer login',
    orConnectWith: 'ou conecte-se com',
    googleBtnText: 'Continuar com o Google',
    alertErrorTitle: 'Atenção',
    alertErrorTitleGeneral: 'Erro',
    alertErrorTitleGoogle: 'Erro no Login',
    errorFieldsRequired: 'Por favor, preencha o e-mail e a senha.',
    errorNameRequired: 'O nome é obrigatório para criar a conta.',
    errorNameMin: 'O nome deve ter pelo menos 3 caracteres.',
    errorEmailRequired: 'O e-mail é obrigatório.',
    errorEmailInvalid: 'Insira um e-mail válido.',
    errorPasswordRequired: 'A senha é obrigatória.',
    errorPasswordMin: 'A senha deve ter pelo menos 6 caracteres.',
    errorConfirmPasswordRequired: 'A confirmação de senha é obrigatória.',
    errorPasswordMismatch: 'As senhas não coincidem.',
    errorGoogleAuthUrl: 'Não foi possível obter a URL de autenticação',
    errorGoogleConnection: 'Ocorreu um problema ao conectar com o Google.',
    errorGeneral: 'Ocorreu um problema na autenticação.',
    successTitle: 'Sucesso!',
    successRegister: 'Conta criada com sucesso. Bem-vindo ao ProTrack!',
  },
  workout: {
    weightHeader: 'CARGA',
    repsHeader: 'REPS',
    restTimerLabel: 'DESCANSO',
    kgPlaceholder: 'kg',
  },
  predefinedWorkouts: {
    sectionTitle: 'Fichas prontas',
    viewDetails: 'Ver ficha',
    modalTitle: 'Detalhes da Ficha',
    useSheetBtn: 'Usar esta ficha',
    successImportMsg: 'Ficha "{name}" adicionada ao seu perfil!',
    errorImportMsg: 'Não foi possível importar esta ficha.',
    sheetSingular: 'Ficha',
    sheetPlural: 'Fichas',
  },
};
